# Generated by Django 5.2 on 2025-04-11 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id_endereco",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "logradouro",
                    models.CharField(db_column="logradouro", max_length=200, null=True),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, db_column="complemento", max_length=200, null=True
                    ),
                ),
                (
                    "bairro",
                    models.CharField(db_column="bairro", max_length=100, null=True),
                ),
                (
                    "cidade",
                    models.CharField(db_column="cidade", max_length=100, null=True),
                ),
                (
                    "estado",
                    models.CharField(db_column="estado", max_length=100, null=True),
                ),
                ("tipo", models.CharField(db_column="tipo", max_length=45, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "endereco",
            },
        ),
    ]
