# Generated by Django 5.2 on 2025-04-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enderecos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endereco",
            name="tipo",
        ),
    ]
