"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
#import os
from pathlib import Path
from decouple import config


#from pymongo import MongoClient

# Cosmos DB Settings
COSMOSDB_URI = config("COSMOSDB_URI")
COSMOSDB_KEY = config("COSMOSDB_KEY")
COSMOSDB_DATABASE_ID = config("COSMOSDB_DATABASE_ID")
COSMOSDB_CONTAINER_ID = config("COSMOSDB_CONTAINER_ID")



"""# Criando a conexão com o CosmosDB
client = MongoClient(COSMOSDB_URI, username='', password=COSMOSDB_PRIMARY_KEY)
cosmos_db = client[COSMOSDB_DATABASE_NAME]"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-uak9-#*zr^u8klhdt1-o1laswn8_4^j+b0b!h#^b1g8h($me9&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Temporariamente permitindo todas as conexões para fins de teste
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    'usuarios', # aplicação para entidade usuário
    'cartoes', # aplicação para entidade cartão de crédito
    'enderecos', # aplicação para entidade endereço e tipo de endereço
    'produtos', # aplicação para entidade produto
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ecommerce_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ecommerce_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {  # Banco de dados padrão (MySQL)
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ibmec-cloud-mall',  # Nome do banco no MySQL
        'USER': 'gabmendes01',  # Usuário do MySQL
        'PASSWORD': 'GabAdmin01#',  # Senha do MySQL
        'HOST': 'ibmec-ecommerce-bigdata-2.mysql.database.azure.com',  # Host do MySQL no Azure
        'PORT': '3306',  # Porta padrão do MySQL
        'OPTIONS': {
            'ssl': {
                'ca': r'C:\Users\gabri\Downloads\BaltimoreCyberTrustRoot.crt.pem',  # Caminho para o certificado SSL
            }
        }
    }
}


#DATABASE_ROUTERS = ['produtos.routers.ProdutoRouter']

# Configuração do Azure Cosmos DB (NoSQL)
"""COSMOS_DB = {
    "ENDPOINT": "https://ibmec-cosmosdb-202307164641.documents.azure.com:443/",
    "PRIMARY_KEY": "5aaddd14-5b11-412f-8766-2cb00d4d6da0",
    "DATABASE_ID": "ibmec-cloud-products",
    "CONTAINER_ID": "produto"
}"""




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
