# Generated by Django 5.1.7 on 2025-04-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id_produto",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estoque", models.PositiveIntegerField()),
                ("categoria", models.CharField(default="Geral", max_length=50)),
                (
                    "imagem_url",
                    models.URLField(default="https://example.com/imagem.jpg"),
                ),
            ],
        ),
    ]
